local STANDARD_DECK_ENUM = {
    StandardCardName = {
            CLUBS_ACE = "CLUBS_ACE",
            CLUBS_TWO = "CLUBS_TWO",
            CLUBS_THREE = "CLUBS_THREE",
            CLUBS_FOUR = "CLUBS_FOUR",
            CLUBS_FIVE = "CLUBS_FIVE",
            CLUBS_SIX = "CLUBS_SIX",
            CLUBS_SEVEN = "CLUBS_SEVEN",
            CLUBS_EIGHT = "CLUBS_EIGHT",
            CLUBS_NINE = "CLUBS_NINE",
            CLUBS_TEN = "CLUBS_TEN",
            CLUBS_JACK = "CLUBS_JACK",
            CLUBS_QUEEN = "CLUBS_QUEEN",
            CLUBS_KING = "CLUBS_KING",
            DIAMONDS_ACE = "DIAMONDS_ACE",
            DIAMONDS_TWO = "DIAMONDS_TWO",
            DIAMONDS_THREE = "DIAMONDS_THREE",
            DIAMONDS_FOUR = "DIAMONDS_FOUR",
            DIAMONDS_FIVE = "DIAMONDS_FIVE",
            DIAMONDS_SIX = "DIAMONDS_SIX",
            DIAMONDS_SEVEN = "DIAMONDS_SEVEN",
            DIAMONDS_EIGHT = "DIAMONDS_EIGHT",
            DIAMONDS_NINE = "DIAMONDS_NINE",
            DIAMONDS_TEN = "DIAMONDS_TEN",
            DIAMONDS_JACK = "DIAMONDS_JACK",
            DIAMONDS_QUEEN = "DIAMONDS_QUEEN",
            DIAMONDS_KING = "DIAMONDS_KING",
            HEARTS_ACE = "HEARTS_ACE",
            HEARTS_TWO = "HEARTS_TWO",
            HEARTS_THREE = "HEARTS_THREE",
            HEARTS_FOUR = "HEARTS_FOUR",
            HEARTS_FIVE = "HEARTS_FIVE",
            HEARTS_SIX = "HEARTS_SIX",
            HEARTS_SEVEN = "HEARTS_SEVEN",
            HEARTS_EIGHT = "HEARTS_EIGHT",
            HEARTS_NINE = "HEARTS_NINE",
            HEARTS_TEN = "HEARTS_TEN",
            HEARTS_JACK = "HEARTS_JACK",
            HEARTS_QUEEN = "HEARTS_QUEEN",
            HEARTS_KING = "HEARTS_KING",
            SPADES_ACE = "SPADES_ACE",
            SPADES_TWO = "SPADES_TWO",
            SPADES_THREE = "SPADES_THREE",
            SPADES_FOUR = "SPADES_FOUR",
            SPADES_FIVE = "SPADES_FIVE",
            SPADES_SIX = "SPADES_SIX",
            SPADES_SEVEN = "SPADES_SEVEN",
            SPADES_EIGHT = "SPADES_EIGHT",
            SPADES_NINE = "SPADES_NINE",
            SPADES_TEN = "SPADES_TEN",
            SPADES_JACK = "SPADES_JACK",
            SPADES_QUEEN = "SPADES_QUEEN",
            SPADES_KING = "SPADES_KING",
            JOKER = "JOKER",
        },

        StandardCardColor = {
            RED = "RED",
            BLACK = "BLACK",
            JOKER = "JOKER",
        },

        StandardCardSuite = {
            CLUBS = "CLUBS",
            DIAMONDS = "DIAMONDS",
            HEARTS = "HEARTS",
            SPADES = "SPADES",
            JOKER = "JOKER",
        },

        StandardCardRank = {
            ACE = "ACE",
            TWO = "TWO",
            THREE = "THREE",
            FOUR = "FOUR",
            FIVE = "FIVE",
            SIX = "SIX",
            SEVEN = "SEVEN",
            EIGHT = "EIGHT",
            NINE = "NINE",
            TEN = "TEN",
            JACK = "JACK",
            QUEEN = "QUEEN",
            KING = "KING",
            JOKER = "JOKER",
        },

        PokerCardRanks = {
            ACE = 1,
            TWO = 2,
            THREE = 3,
            FOUR = 4,
            FIVE = 5,
            SIX = 6,
            SEVEN = 7,
            EIGHT = 8,
            NINE = 9,
            TEN = 10,
            JACK = 11,
            QUEEN = 12,
            KING = 13,
        },
};

return STANDARD_DECK_ENUM;